package ir.arman.domain;

import io.quarkus.hibernate.reactive.panache.PanacheEntityBase;
import io.quarkus.security.jpa.Password;
import io.quarkus.security.jpa.Roles;
import io.quarkus.security.jpa.UserDefinition;
import io.quarkus.security.jpa.Username;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * An account. Backs both UserProfile and TeamMember -- the spec exposes the same row
 * through two shapes, so there is one table behind them.
 *
 * Ids are prefixed strings drawn from users_id_seq, not generated by Hibernate; see
 * the repository. Schema lives in the Liquibase changelog, never here.
 *
 * {@code @UserDefinition} is the security-jpa contract: it tells the extension which
 * columns hold the login identifier, the password hash and the roles, and in exchange
 * the extension verifies credentials against them. The annotations are declarations
 * about existing columns -- none of them changes the schema.
 */
@Entity
@Table(name = "users")
@UserDefinition
public class User extends PanacheEntityBase {

    public static final String ID_PREFIX = "usr_";
    public static final String ID_SEQUENCE = "users_id_seq";

    /**
     * TeamMember.status for a usable account. The spec gives the field no enum and no
     * endpoint that writes it, so it changes only against the database directly.
     *
     * <p>Here rather than in the one resource that used to own it because there are now
     * two writers of {@link #status}: registration and the startup bootstrap. Two literal
     * {@code "active"}s in two packages is how the login check and the account creation
     * drift apart.
     */
    public static final String STATUS_ACTIVE = "active";

    @Id
    public String id;

    /** The login identifier: LoginRequest.studentId. */
    @Username
    @Column(name = "student_id", nullable = false, unique = true)
    public String studentId;

    @Column(nullable = false)
    public String name;

    /**
     * Optional: registration collects a name, a student id and a password only, so an
     * account exists before it has an address. Still unique -- Postgres permits many
     * NULLs in a unique index. See changelog 003.
     */
    @Column(unique = true)
    public String email;

    /**
     * Never leaves the domain layer -- no DTO exposes it.
     *
     * <p>{@code @Password} defaults to bcrypt in Modular Crypt Format, which is what
     * {@code BcryptUtil.bcryptHash} writes and what the seed contains, so the column
     * needs no conversion: {@code $2a$10$<salt><digest>}, cost and salt carried inline.
     */
    @Password
    @Column(name = "password_hash", nullable = false)
    public String passwordHash;

    @Column(nullable = false)
    public Role role;

    /**
     * The same {@code role} column again, as the plain String that {@code @Roles}
     * requires -- it accepts a String or a collection of them, never an enum.
     *
     * <p>Read-only ({@code insertable = false, updatable = false}) so there is exactly
     * one writer for the column: {@link #role}. Without that, two fields would race to
     * define the same column and Hibernate would reject the mapping outright.
     */
    @Roles
    @Column(name = "role", insertable = false, updatable = false)
    public String roleName;

    public String avatar;

    @Column(nullable = false)
    public Theme theme;

    @Column(nullable = false)
    public Language language;

    @Column(name = "notifications_enabled", nullable = false)
    public boolean notificationsEnabled;

    /**
     * TeamMember.status. The spec gives it no enum, so it stays a free string and is
     * not modelled as one of the types in this package.
     */
    @Column(nullable = false)
    public String status;

    @Column(name = "created_at", nullable = false)
    public Instant createdAt;
}
