package ir.arman.domain;

import io.quarkus.hibernate.reactive.panache.PanacheEntityBase;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * An account. Backs both UserProfile and TeamMember -- the spec exposes the same row
 * through two shapes, so there is one table behind them.
 *
 * Ids are prefixed strings drawn from users_id_seq, not generated by Hibernate; see
 * the repository. Schema lives in the Liquibase changelog, never here.
 */
@Entity
@Table(name = "users")
public class User extends PanacheEntityBase {

    public static final String ID_PREFIX = "usr_";
    public static final String ID_SEQUENCE = "users_id_seq";

    @Id
    public String id;

    /** The login identifier: LoginRequest.studentId. */
    @Column(name = "student_id", nullable = false, unique = true)
    public String studentId;

    @Column(nullable = false)
    public String name;

    @Column(nullable = false, unique = true)
    public String email;

    /** Never leaves the domain layer -- no DTO exposes it. */
    @Column(name = "password_hash", nullable = false)
    public String passwordHash;

    @Column(nullable = false)
    public Role role;

    public String avatar;

    @Column(nullable = false)
    public Theme theme;

    @Column(nullable = false)
    public Language language;

    @Column(name = "notifications_enabled", nullable = false)
    public boolean notificationsEnabled;

    /**
     * TeamMember.status. The spec gives it no enum, so it stays a free string and is
     * not modelled as one of the types in this package.
     */
    @Column(nullable = false)
    public String status;

    @Column(name = "created_at", nullable = false)
    public Instant createdAt;
}
